export const INCREMENT_COUNTER = 'INCREMENT_COUNTER'
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER'
export const INCREMENT_AMOUNT = 'INCREMENT_AMOUNT'
export const CHANGE_TOTAL = 'CHANGE_TOTAL'
